name: Deploy to GitHub Pages
# trigger on pushes to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write        # allow publishing
      id-token: write     # required for configure-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # If you have a build step (e.g. npm run build), add it here.
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build site
      #   run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./         # deploy everything in repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
